name: Deploy Python Lambda to LocalStack

on:
  push:
    branches: [ feature ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies and Zip
        run: |
          mkdir -p package
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t package/;
          fi
          cp -r lambda.function/. package/

          cd package && zip -r ../function.zip .
      - name: Deploy to LocalStack
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: ap-northeast-1
          ENDPOINT_URL: http://localhost:4566
        run: |
          aws --endpoint-url=$ENDPOINT_URL s3 mb s3://s3-test-bucket

          aws --endpoint-url=$ENDPOINT_URL s3 cp function.zip s3://s3-test-bucket/function.zip

          if aws ----endpoint-url=$ENDPOINT_URL lambda get function --function-name lambda-function > /dev/null 2>&1; then
           aws --endpoint-url=$$ENDPOINT_URL lambda update-function-code \
             -- function-name lambda-function \
             --s3-bucket s3-test-bucket \
             --s3-key function.zip
          else
            aws --endpoint-url=$ENDPOINT_URL lambda create-function \
              --function-name lambda-function \
              --runtime python3.9 \
              --role arn:aws:iam::000000000000:role/lambda-role \
              --handler lambda_function.lambda_handler \
              --code S3Bucket=s3-test-bucket,S3Key=function.zip
          fi

          echo "Waiting for function to become Active..."
          aws --endpoint-url=$ENDPOINT_URL lambda wait function-active-v2 --function-name lambda-function

          aws --endpoint-url=$ENDPOINT_URL lambda update-function-code \
            --function-name lambda-function \
            --s3-bucket s3-test-bucket \
            --s3-key function.zip