name: Deploy Python Lambda to LocalStack

on:
  push:
    branches: [ feature ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies and Zip
        run: |
          mkdir -p package
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t package/;
          fi
          cp -r lambda.function/. package/

          cd package && zip -r ../function.zip .
      - name: Deploy to LocalStack
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: ap-northeast-1
          ENDPOINT_URL: http://localhost:4566
        run: |
          aws --endpoint-url=$ENDPOINT_URL s3 cp function.zip s3://s3-test-bucket/function.zip
          aws --endpoint-url=$ENDPOINT_URL lambda update-function-code \
            --function-name my-function \
            --s3-bucket s3-test-bucket \
            --s3-key function.zip